"""Build the content bundle the frontend loads.

    python tools/build.py

Writes web/public/content/bundle.json and web/src/content/schema.ts. Every
generated problem is validated first; the build fails loudly rather than
emitting a level that could mislead the learner.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
CONTENT = ROOT / "content" / "chapters"
BUNDLE_OUT = ROOT / "web" / "public" / "content" / "bundle.json"
TYPES_OUT = ROOT / "web" / "src" / "content" / "schema.ts"

sys.path.insert(0, str(TOOLS))

from mathcoach.schema import SCHEMA_VERSION, Bundle, Chapter  # noqa: E402
from mathcoach.validate import ValidationError, check_bundle  # noqa: E402

# Chapters are built in this order; it is also the campaign order.
CHAPTER_DIRS = (
    "01-rust-remover",
    "02-rearranging",
    "03-machines",
    "04-growth",
    "05-circles",
    "06-approaching",
    "07-slope",
    "08-rulebook",
    "09-chain-rule",
    "10-hidden",
    "11-bottom",
    "11a-consolidation",
    "12-backwards",
    "13-bridge",
    "14-costume",
    "15-trading",
    "16-expectations",
    "16a-consolidation",
)

ACTS = {
    1: "Reflexes",
    2: "Change",
    3: "Accumulation",
}

# The placement quiz lives beside the chapters it reports on.
DIAGNOSTIC_DIR = "00-diagnostic"


def _load_module(dirname: str, module: str):
    """Import content/chapters/<dirname>/<module>.py as part of a package."""
    package_dir = CONTENT / dirname
    module_path = package_dir / f"{module}.py"
    if not module_path.exists():
        raise FileNotFoundError(f"no {module}.py in {package_dir}")

    package_name = f"chapter_{dirname.replace('-', '_')}"
    if package_name not in sys.modules:
        package_spec = importlib.util.spec_from_file_location(
            package_name,
            package_dir / "__init__.py",
            submodule_search_locations=[str(package_dir)],
        )
        if package_spec is None or package_spec.loader is None:
            raise ImportError(f"cannot load package for {dirname}")
        package = importlib.util.module_from_spec(package_spec)
        sys.modules[package_name] = package
        package_spec.loader.exec_module(package)

    full_name = f"{package_name}.{module}"
    module_spec = importlib.util.spec_from_file_location(full_name, module_path)
    if module_spec is None or module_spec.loader is None:
        raise ImportError(f"cannot load {full_name}")
    loaded = importlib.util.module_from_spec(module_spec)
    sys.modules[full_name] = loaded
    module_spec.loader.exec_module(loaded)
    return loaded


TYPES_TEMPLATE = '''// GENERATED by tools/build.py - do not edit.
// Run `python tools/build.py` after changing tools/mathcoach/schema.py.

export const SCHEMA_VERSION = {schema_version};

export type LevelType = "concept" | "choice" | "decompose" | "solve";
export type Tier = "easy" | "medium" | "hard" | "challenge";

/**
 * An expression sampled at fixed points. Multivariable: `points[i]` is a tuple
 * aligned to `variables`. See tools/mathcoach/fingerprint.py.
 */
export interface Fingerprint {{
  variables: string[];
  points: number[][];
  ys: number[];
  /** Antiderivatives are only defined up to +C; compare differences instead. */
  upToConstant: boolean;
}}

export interface Distractor {{
  id: string;
  fingerprint: Fingerprint;
  /** Names the specific misconception this wrong answer reveals. */
  feedback: string;
}}

export interface Step {{
  latex: string;
  note: string;
}}

export interface Answer {{
  label: string;
  latex: string;
  fingerprint: Fingerprint;
  distractors: Distractor[];
  /** Shown under the input, e.g. "a number" or "in terms of x". */
  hintText: string;
}}

export interface Choice {{
  id: string;
  label: string;
  isLatex: boolean;
  feedback: string;
}}

export interface Problem {{
  id: string;
  templateId: string;
  tier: Tier;
  instruction: string;
  promptLatex: string;
  answers: Answer[];
  hints: string[];
  steps: Step[];
  /** Variables a typed answer may use. */
  variables: string[];
  /** Standing assumption shown with the prompt, e.g. "assume x, y > 0". */
  assumption: string;
  /** `choice` problems only. */
  choices?: Choice[];
  correctChoice?: string | null;
}}

export interface Level {{
  id: string;
  type: LevelType;
  title: string;
  blurb: string;
  problems: Problem[];
  /** `concept` levels only: Markdown with $...$ math. */
  bodyMd?: string;
}}

export interface Chapter {{
  id: string;
  number: number;
  act: number;
  name: string;
  tag: string;
  /** The mastery gate from the roadmap. */
  gate: string;
  /** Advisory ordering. Nothing is hard-locked. */
  requires: string[];
  /** Whether the diagnostic may mark this chapter as already known. */
  skippable: boolean;
  subtitle: string;
  /** A consolidation tier: drawn with a star, and excluded from gap detection. */
  isConsolidation: boolean;
  levels: Level[];
}}

export interface DiagnosticItem {{
  problem: Problem;
  chapterId: string;
  /** What this item tests, for the results readout. */
  skill: string;
}}

export interface Diagnostic {{
  id: string;
  title: string;
  blurb: string;
  /** Fraction of a chapter's items needed to mark it known. */
  passThreshold: number;
  items: DiagnosticItem[];
}}

export interface Bundle {{
  schemaVersion: number;
  /** Suggested time per tier, in seconds. 0 means open-ended. Never enforced. */
  tierSeconds: Record<Tier, number>;
  /** Act number -> act title. */
  acts: Record<string, string>;
  chapters: Chapter[];
  diagnostic: Diagnostic | null;
}}
'''


def emit_types() -> None:
    TYPES_OUT.parent.mkdir(parents=True, exist_ok=True)
    TYPES_OUT.write_text(
        TYPES_TEMPLATE.format(schema_version=SCHEMA_VERSION), encoding="utf-8"
    )
    print(f"  types   -> {TYPES_OUT.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--types-only",
        action="store_true",
        help="regenerate the TypeScript schema without building content",
    )
    args = parser.parse_args()

    print("MathCoach content build")

    if args.types_only:
        emit_types()
        return 0

    chapters: list[Chapter] = []
    for dirname in CHAPTER_DIRS:
        chapter = _load_module(dirname, "chapter").build()
        levels = len(chapter.levels)
        problems = sum(len(level.problems) for level in chapter.levels)
        print(
            f"  ch {chapter.number:>2}  {chapter.name:<24}"
            f"{levels} levels, {problems:>3} problems"
        )
        chapters.append(chapter)

    diagnostic = _load_module(DIAGNOSTIC_DIR, "diagnostic").build()
    print(f"  diagnostic  {len(diagnostic.items)} items")

    bundle = Bundle(chapters=tuple(chapters), diagnostic=diagnostic, acts=ACTS)

    try:
        check_bundle(bundle)
    except ValidationError as exc:
        print(f"\nVALIDATION FAILED\n{exc}", file=sys.stderr)
        return 1

    payload = bundle.to_dict()
    BUNDLE_OUT.parent.mkdir(parents=True, exist_ok=True)
    BUNDLE_OUT.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    total_problems = sum(
        len(level["problems"]) for c in payload["chapters"] for level in c["levels"]
    )
    total_distractors = sum(
        len(answer["distractors"])
        for c in payload["chapters"]
        for level in c["levels"]
        for problem in level["problems"]
        for answer in problem["answers"]
    )

    print(
        f"  validated {total_problems} problems + {len(diagnostic.items)} "
        f"diagnostic items, {total_distractors} distractors"
    )
    print(
        f"  bundle  -> {BUNDLE_OUT.relative_to(ROOT)} "
        f"({BUNDLE_OUT.stat().st_size // 1024} KB)"
    )
    emit_types()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
